"""Initial migration

Revision ID: 6683b13be94e
Revises: 
Create Date: 2026-06-28 20:35:22.356031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6683b13be94e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('equip_description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'TRIPPED', 'ALARM', 'UNKNOWN', name='equipment_status_enum'), nullable=True),
    sa.Column('io_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('alarm',
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('alarm_type', sa.String(), nullable=True),
    sa.Column('alarm_active', sa.Boolean(), nullable=True),
    sa.Column('alarm_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('alarm_descr', sa.String(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['equipments.tag_id'], ),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    op.create_index(op.f('ix_alarm_alarm_id'), 'alarm', ['alarm_id'], unique=False)
    op.create_table('analog_tags',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('process_val', sa.Float(), nullable=True),
    sa.Column('param_unit', sa.String(), nullable=True),
    sa.Column('l1_val', sa.Float(), nullable=True),
    sa.Column('l2_val', sa.Float(), nullable=True),
    sa.Column('h1_val', sa.Float(), nullable=True),
    sa.Column('h2_val', sa.Float(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['equipments.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('digital_tags',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('binary_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['equipments.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('group_status',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('binary_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['equipments.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_status')
    op.drop_table('digital_tags')
    op.drop_table('analog_tags')
    op.drop_index(op.f('ix_alarm_alarm_id'), table_name='alarm')
    op.drop_table('alarm')
    op.drop_table('equipments')
    # ### end Alembic commands ###
